### ISSUE TITLE
Vector value seem  rounded

### ISSUE THREAD

**Issue by tenpigs267** [qdrant/java-client#19] opened 2024-01-21 21:33 UTC
Hello,
I'm currently trying to add a QDrantEmbeddingStore to Lanchain4J (https://github.com/langchain4j) but I have a problem.
IT with testContainer keep failing because some Vector values seem rounded : 
expected: Embedding { vector = [-0.086097434, 0.033505224, 0.017902793, ...
 but was: Embedding { vector = [-0.08609743, 0.03350522, 0.017902792, ...

I don't know if it can be related to quantization, I did'nt enable quantization (but maybe it is enabled by default)
If anyone have a hint that would be appreciated.
Thanks

**Comment by Anush008** [comment] 2024-01-29 01:38
Hi @tenpigs267. I too ran into a similar issue when implementing https://github.com/langchain4j/langchain4j/pull/542. Not on my machine, but the reviewers. Not quite sure why something like this would happen, that too inconsitently.

**Comment by tenpigs267** [comment] 2024-01-30 14:59
Hi @Anush008,
I thought that it was related to quantization (as stated here, quantization can lead to a loss of precision https://qdrant.tech/articles/scalar-quantization/). But if you say that this problem doesn't show up on your machine it is weirder... maybe more related to rounding (a different FPU?).
For history my PC is a i7-13620H with 16Gb of RAM

**Comment by Anush008** [comment] 2024-01-30 15:01
Hey @tenpigs267. Nice to meet you.
To make it weirder, refer to this comment.

https://github.com/langchain4j/langchain4j/pull/542#issuecomment-1910640906

**Comment by Anush008** [comment] 2024-05-19 04:00
Closing for the time being since we haven't been able to reproduce this.

Feel free to re-open if needed.

**Closed by Anush008** 2024-05-19 04:00 UTC
