### ISSUE TITLE
I had to add "implementation("com.google.protobuf:protobuf-java:3.24.0")"

### ISSUE THREAD

**Issue by slaszu** [qdrant/java-client#40] opened 2024-06-05 20:55 UTC
I use kotlin. I had to add line `implementation("com.google.protobuf:protobuf-java:3.24.0")` to my `build.gradle.kts` to make qdrant java-client works.  

Now I have this 2 lines:  
```
implementation("io.qdrant:client:1.9.1")
implementation("com.google.protobuf:protobuf-java:3.24.0")
```

Secund think, I had to use exacly version 3.24.0, witch is pointed in https://github.com/qdrant/java-client/blob/master/build.gradle#L81

Maybe it because kotlin, but I think it is worth to say it in documentation.

**Comment by Anush008** [comment] 2024-06-28 13:22
`com.google.protobuf:protobuf-java:3.24.0` shouldn't be required.

Could you please describe more about the error/issue you ran into?

**Comment by Loahrs** [comment] 2024-07-03 08:42
Thank you, slazu! 

I encountered the same problem. I also use Kotlin in my project with the newest qdrant-Client (1.10.0). 

I was trying to do a search:

```
val searchResults : List<ScoredPoint> =
        client.searchAsync(
            SearchPoints.newBuilder()
                .setCollectionName("my_dataset")
                .setLimit(3)
                .addAllVector(...)
                .setWithPayload(enable(true))
                .build()
        ).get()
```

But then encountered the following errors in my IDE:
![qdrant](https://github.com/qdrant/java-client/assets/20272232/02a640e2-29b0-40b1-ab07-418085e43b4d)


Adding the protobuf-Dependency fixed the errors for me.

**Comment by Anush008** [comment] 2024-07-03 08:45
I expected it to be bundled with the project dependencies.
It seems like, it might be useful to add this as a side note for users.
Thanks

**Comment by Loahrs** [comment] 2024-07-03 12:49
> I expected it to be bundled with the project dependencies. It seems like, it might be useful to add this as a side note for users. Thanks

As far as I know you would have to change the way your dependencies are added in your gradle.build, if you want to have these dependencies available transitively. 

The libraries dependencies are defined this way:

```
dependencies {
	errorprone "com.uber.nullaway:nullaway:0.10.18"

	implementation "io.grpc:grpc-protobuf:${grpcVersion}"
	implementation "io.grpc:grpc-services:${grpcVersion}"
	implementation "io.grpc:grpc-stub:${grpcVersion}"
	implementation "com.google.guava:guava:30.1-jre"
	implementation "org.slf4j:slf4j-api:${slf4jVersion}"

        //...
}
```

note that they are imported using `implementation "..." `. 
This means your libraries are available during development, but won't be automatically made accessible to a user of the library. 

The issue is that the client libraries methods return Guava-Objects. So Guava-Classes are part of your public facing api and thus part of the library. E.g:

```
public ListenableFuture<Points.ScoredPoint>> searchAsync(Points.SearchPoints request) {
    // -> returns a Guava Listenable from com.google.common.util.concurrent
}
```

Gradle allows defining dependencies using `api "..."` which makes dependencies transitive:

```
dependencies {
	errorprone "com.uber.nullaway:nullaway:0.10.18"

	api "io.grpc:grpc-protobuf:${grpcVersion}"
	implementation "io.grpc:grpc-services:${grpcVersion}"
	implementation "io.grpc:grpc-stub:${grpcVersion}"
	api "com.google.guava:guava:30.1-jre"
	implementation "org.slf4j:slf4j-api:${slf4jVersion}"

        //...
}
```

A cleaner approach could be to abstract away third party dependencies on public facing api. 

See: https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_separation

Also note the explanation here: https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_recognizing_dependencies

**Comment by Anush008** [comment] 2024-07-03 13:02
`io.grpc:grpc-protobuf` indeed needs to be included in your project.

OP mentioned about missing `com.google.protobuf:protobuf-java`, which for me is weird since I expected it to be available with the above.

**Comment by Anush008** [comment] 2024-07-03 13:05
Anyways, a note about these dependencies for consumers would be useful. Will do.
Thank you @slaszu and @Loahrs

**Comment by Loahrs** [comment] 2024-07-03 13:13
> `io.grpc:grpc-protobuf` indeed needs to be included in your project.
> 
> OP mentioned about missing `com.google.protobuf:protobuf-java`, which for me is weird since I expected it to be available with the above.

I also had to add the Guava library in my case. The missing `com.google.protobuf:protobuf-java` should be following the same logic as in my last comment - Because SearchPoints extends a Protobuf-Class but is part of the public API of this library. 

But just adding a note about the needed dependencies might be a simpler thing to indeed :)

**Comment by p-dekker** [comment] 2024-07-05 18:43
Using maven and java, I also have issues with class not accessible using the simple  example from the readme. 

I do have the tensorflow java bindings as well, so maybe they case havoc as they also use grpc libs.

**Comment by Anush008** [comment] 2024-07-16 09:38
Resolved with https://github.com/qdrant/java-client#gradle

**Closed by Anush008** 2024-07-16 09:38 UTC

**Comment by sven42** [comment] 2025-02-12 11:14
Hi @Anush008,

thank you for describing a workaround in the Readme.md.

However, I think it would be better to fix the issue by using the right scopes for the dependencies as suggested by @Loahrs :

```
        api "io.grpc:grpc-protobuf:${grpcVersion}"
	implementation "io.grpc:grpc-services:${grpcVersion}"
	implementation "io.grpc:grpc-stub:${grpcVersion}"
	api "com.google.guava:guava:30.1-jre"
	implementation "org.slf4j:slf4j-api:${slf4jVersion}"
```
